import type { Client } from './types';

// Dates are relative to module-load time so the mock pipeline always
// looks "fresh" without manual updates. Mock data is server-only
// (gated by USE_MOCK_DATA in lib/data.ts), so this never hydrates.
const TODAY = new Date();

function daysAgo(n: number): string {
  const d = new Date(TODAY);
  d.setDate(d.getDate() - n);
  return d.toISOString().slice(0, 10);
}

function paddedId(prefix: string, n: number): string {
  return `${prefix}-${String(n).padStart(4, '0')}`;
}

type Required = Pick<
  Client,
  | 'srNo'
  | 'clientName'
  | 'email'
  | 'mobile'
  | 'reference'
  | 'incomeSource'
  | 'status'
>;

function client(fields: Required & Partial<Client>): Client {
  return {
    contactId: paddedId('CON', fields.srNo),
    campaignSent: null,
    replied: null,
    autoReplySent: null,
    formSubmitted: null,
    invoiceId: '',
    invoiceCreated: null,
    invoiceAmount: null,
    fu1Sent: null,
    fu2Sent: null,
    fu3Sent: null,
    lastFollowUpDate: null,
    paymentReceived: null,
    onboardingFormSent: null,
    onboardingFormSubmitted: null,
    notes: '',
    oneDriveFolderId: `01FOLDER${fields.srNo.toString().padStart(4, '0')}`,
    oneDriveFileId: `01FILE${fields.srNo.toString().padStart(4, '0')}`,
    ...fields,
  };
}

const REFS = ['Varun Kalia', 'Jimit Doshi', 'Sohil Patel'];
const ref = (i: number) => REFS[i % REFS.length];

// Bucket 1 — only campaign sent (5)
const bucketCampaignOnly: Client[] = [
  client({
    srNo: 1,
    clientName: 'Aniket Powar',
    email: 'aniket.powar@gmail.com',
    mobile: '0412 334 901',
    reference: ref(0),
    incomeSource: 'Salary',
    status: 'Campaign Sent',
    campaignSent: daysAgo(2),
  }),
  client({
    srNo: 2,
    clientName: 'Priya Sharma',
    email: 'priya.sharma88@outlook.com',
    mobile: '0423 776 102',
    reference: ref(1),
    incomeSource: 'Salary + Investment',
    status: 'Campaign Sent',
    campaignSent: daysAgo(3),
  }),
  client({
    srNo: 3,
    clientName: 'Lachlan Murphy',
    email: 'lachlan.m@gmail.com',
    mobile: '0431 559 008',
    reference: ref(2),
    incomeSource: 'Salary',
    status: 'Campaign Sent',
    campaignSent: daysAgo(4),
  }),
  client({
    srNo: 4,
    clientName: 'Ravi Iyer',
    email: 'r.iyer.au@gmail.com',
    mobile: '0404 220 715',
    reference: ref(0),
    incomeSource: 'Business',
    status: 'Campaign Sent',
    campaignSent: daysAgo(5),
  }),
  client({
    srNo: 5,
    clientName: 'Emma Chen',
    email: 'emma.chen23@outlook.com',
    mobile: '0455 188 340',
    reference: ref(1),
    incomeSource: 'Salary + Rental',
    status: 'Campaign Sent',
    campaignSent: daysAgo(6),
  }),
];

// Bucket 2 — campaign + replied (4)
const bucketReplied: Client[] = [
  client({
    srNo: 6,
    clientName: 'Rohan Mehta',
    email: 'rohan.mehta@gmail.com',
    mobile: '0418 992 651',
    reference: ref(2),
    incomeSource: 'Salary',
    status: 'Replied - Awaiting Call',
    campaignSent: daysAgo(10),
    autoReplySent: daysAgo(8),
    replied: daysAgo(8),
  }),
  client({
    srNo: 7,
    clientName: "Sarah O'Connor",
    email: 'sarah.oconnor@outlook.com',
    mobile: '0429 311 047',
    reference: ref(0),
    incomeSource: 'Salary + Investment',
    status: 'Replied - Awaiting Call',
    campaignSent: daysAgo(9),
    autoReplySent: daysAgo(7),
    replied: daysAgo(7),
  }),
  client({
    srNo: 8,
    clientName: 'Aditya Verma',
    email: 'aditya.verma@gmail.com',
    mobile: '0411 800 226',
    reference: ref(1),
    incomeSource: 'Salary',
    status: 'Replied - Awaiting Call',
    campaignSent: daysAgo(11),
    autoReplySent: daysAgo(6),
    replied: daysAgo(6),
  }),
  client({
    srNo: 9,
    clientName: 'Isha Kapoor',
    email: 'isha.kapoor@outlook.com',
    mobile: '0426 543 902',
    reference: ref(2),
    incomeSource: 'Salary + Rental',
    status: 'Replied - Awaiting Call',
    campaignSent: daysAgo(12),
    autoReplySent: daysAgo(4),
    replied: daysAgo(4),
  }),
];

// Bucket 3 — through form submitted (4)
const bucketFormSubmitted: Client[] = [
  client({
    srNo: 10,
    clientName: 'Vikram Singh',
    email: 'vikram.singh@gmail.com',
    mobile: '0432 117 605',
    reference: ref(0),
    incomeSource: 'Business',
    status: 'Invoice Sent',
    campaignSent: daysAgo(15),
    autoReplySent: daysAgo(13),
    replied: daysAgo(13),
    formSubmitted: daysAgo(11),
  }),
  client({
    srNo: 11,
    clientName: 'Olivia Bennett',
    email: 'olivia.bennett@outlook.com',
    mobile: '0408 740 219',
    reference: ref(1),
    incomeSource: 'Salary',
    status: 'Invoice Sent',
    campaignSent: daysAgo(14),
    autoReplySent: daysAgo(12),
    replied: daysAgo(12),
    formSubmitted: daysAgo(10),
  }),
  client({
    srNo: 12,
    clientName: 'Kunal Joshi',
    email: 'kunal.joshi@gmail.com',
    mobile: '0420 661 558',
    reference: ref(2),
    incomeSource: 'Salary + Investment',
    status: 'Invoice Sent',
    campaignSent: daysAgo(16),
    autoReplySent: daysAgo(14),
    replied: daysAgo(14),
    formSubmitted: daysAgo(9),
  }),
  client({
    srNo: 13,
    clientName: 'Megha Reddy',
    email: 'megha.reddy@gmail.com',
    mobile: '0413 882 770',
    reference: ref(0),
    incomeSource: 'Salary',
    status: 'Invoice Sent',
    campaignSent: daysAgo(13),
    autoReplySent: daysAgo(11),
    replied: daysAgo(11),
    formSubmitted: daysAgo(7),
  }),
];

// Bucket 4 — invoice created, no follow-ups yet (4)
const bucketInvoiceSent: Client[] = [
  client({
    srNo: 14,
    clientName: 'Dhruv Patel',
    email: 'dhruv.patel@gmail.com',
    mobile: '0421 559 880',
    reference: ref(1),
    incomeSource: 'Salary + Rental',
    status: 'Invoice Sent',
    campaignSent: daysAgo(18),
    autoReplySent: daysAgo(16),
    replied: daysAgo(16),
    formSubmitted: daysAgo(14),
    invoiceId: 'INV-2026-0014',
    invoiceCreated: daysAgo(5),
    invoiceAmount: 199,
    fu1Sent: 'no',
    fu2Sent: 'no',
    fu3Sent: 'no',
    paymentReceived: 'no',
  }),
  client({
    srNo: 15,
    clientName: 'Hannah Wilson',
    email: 'hannah.wilson@outlook.com',
    mobile: '0445 320 117',
    reference: ref(2),
    incomeSource: 'Salary',
    status: 'Invoice Sent',
    campaignSent: daysAgo(17),
    autoReplySent: daysAgo(15),
    replied: daysAgo(15),
    formSubmitted: daysAgo(13),
    invoiceId: 'INV-2026-0015',
    invoiceCreated: daysAgo(4),
    invoiceAmount: 149,
    fu1Sent: 'no',
    fu2Sent: 'no',
    fu3Sent: 'no',
    paymentReceived: 'no',
  }),
  client({
    srNo: 16,
    clientName: 'Arjun Nair',
    email: 'arjun.nair@gmail.com',
    mobile: '0407 882 145',
    reference: ref(0),
    incomeSource: 'Business',
    status: 'Invoice Sent',
    campaignSent: daysAgo(20),
    autoReplySent: daysAgo(18),
    replied: daysAgo(18),
    formSubmitted: daysAgo(15),
    invoiceId: 'INV-2026-0016',
    invoiceCreated: daysAgo(6),
    invoiceAmount: 349,
    fu1Sent: 'no',
    fu2Sent: 'no',
    fu3Sent: 'no',
    paymentReceived: 'no',
  }),
  client({
    srNo: 17,
    clientName: 'Neha Saxena',
    email: 'neha.saxena@outlook.com',
    mobile: '0432 091 778',
    reference: ref(1),
    incomeSource: 'Salary + Investment',
    status: 'Invoice Sent',
    campaignSent: daysAgo(16),
    autoReplySent: daysAgo(14),
    replied: daysAgo(14),
    formSubmitted: daysAgo(11),
    invoiceId: 'INV-2026-0017',
    invoiceCreated: daysAgo(3),
    invoiceAmount: 249,
    fu1Sent: 'no',
    fu2Sent: 'no',
    fu3Sent: 'no',
    paymentReceived: 'no',
  }),
];

// Bucket 5 — FU1 sent (3) — invoice > 9 days, fu1 within last week
const bucketFU1: Client[] = [
  client({
    srNo: 18,
    clientName: 'Saurabh Gupta',
    email: 'saurabh.gupta@gmail.com',
    mobile: '0411 226 998',
    reference: ref(2),
    incomeSource: 'Salary',
    status: 'Follow Up 1 Sent',
    campaignSent: daysAgo(25),
    autoReplySent: daysAgo(23),
    replied: daysAgo(23),
    formSubmitted: daysAgo(20),
    invoiceId: 'INV-2026-0018',
    invoiceCreated: daysAgo(12),
    invoiceAmount: 179,
    fu1Sent: daysAgo(3),
    fu2Sent: 'no',
    fu3Sent: 'no',
    lastFollowUpDate: daysAgo(3),
    paymentReceived: 'no',
  }),
  client({
    srNo: 19,
    clientName: 'Chloe Walker',
    email: 'chloe.walker@outlook.com',
    mobile: '0436 770 158',
    reference: ref(0),
    incomeSource: 'Salary + Rental',
    status: 'Follow Up 1 Sent',
    campaignSent: daysAgo(24),
    autoReplySent: daysAgo(22),
    replied: daysAgo(22),
    formSubmitted: daysAgo(19),
    invoiceId: 'INV-2026-0019',
    invoiceCreated: daysAgo(11),
    invoiceAmount: 219,
    fu1Sent: daysAgo(2),
    fu2Sent: 'no',
    fu3Sent: 'no',
    lastFollowUpDate: daysAgo(2),
    paymentReceived: 'no',
  }),
  client({
    srNo: 20,
    clientName: 'Karthik Raman',
    email: 'karthik.raman@gmail.com',
    mobile: '0408 311 660',
    reference: ref(1),
    incomeSource: 'Salary',
    status: 'Follow Up 1 Sent',
    campaignSent: daysAgo(26),
    autoReplySent: daysAgo(24),
    replied: daysAgo(24),
    formSubmitted: daysAgo(21),
    invoiceId: 'INV-2026-0020',
    invoiceCreated: daysAgo(13),
    invoiceAmount: 99,
    fu1Sent: daysAgo(4),
    fu2Sent: 'no',
    fu3Sent: 'no',
    lastFollowUpDate: daysAgo(4),
    paymentReceived: 'no',
  }),
];

// Bucket 6 — FU2 sent (2)
const bucketFU2: Client[] = [
  client({
    srNo: 21,
    clientName: 'Rachit Kumar',
    email: 'rachit.kumar@gmail.com',
    mobile: '0419 558 220',
    reference: ref(2),
    incomeSource: 'Business',
    status: 'Follow Up 2 Sent',
    campaignSent: daysAgo(28),
    autoReplySent: daysAgo(26),
    replied: daysAgo(26),
    formSubmitted: daysAgo(23),
    invoiceId: 'INV-2026-0021',
    invoiceCreated: daysAgo(17),
    invoiceAmount: 299,
    fu1Sent: daysAgo(10),
    fu2Sent: daysAgo(3),
    fu3Sent: 'no',
    lastFollowUpDate: daysAgo(3),
    paymentReceived: 'no',
  }),
  client({
    srNo: 22,
    clientName: 'Liam Foster',
    email: 'liam.foster@outlook.com',
    mobile: '0426 882 119',
    reference: ref(0),
    incomeSource: 'Salary',
    status: 'Follow Up 2 Sent',
    campaignSent: daysAgo(27),
    autoReplySent: daysAgo(25),
    replied: daysAgo(25),
    formSubmitted: daysAgo(22),
    invoiceId: 'INV-2026-0022',
    invoiceCreated: daysAgo(16),
    invoiceAmount: 159,
    fu1Sent: daysAgo(9),
    fu2Sent: daysAgo(2),
    fu3Sent: 'no',
    lastFollowUpDate: daysAgo(2),
    paymentReceived: 'no',
  }),
];

// Bucket 7 — FU3 sent + lost (2) — final status flips to Lost - Manual Review
const bucketLost: Client[] = [
  client({
    srNo: 23,
    clientName: 'Suresh Pillai',
    email: 'suresh.pillai@gmail.com',
    mobile: '0432 117 008',
    reference: ref(1),
    incomeSource: 'Salary + Investment',
    status: 'Lost - Manual Review',
    campaignSent: daysAgo(30),
    autoReplySent: daysAgo(28),
    replied: daysAgo(28),
    formSubmitted: daysAgo(25),
    invoiceId: 'INV-2026-0023',
    invoiceCreated: daysAgo(20),
    invoiceAmount: 199,
    fu1Sent: daysAgo(14),
    fu2Sent: daysAgo(8),
    fu3Sent: daysAgo(3),
    lastFollowUpDate: daysAgo(3),
    paymentReceived: 'no',
    notes: 'Three follow-ups, no response. Marked for manual review.',
  }),
  client({
    srNo: 24,
    clientName: 'Tom Anderson',
    email: 'tom.anderson@outlook.com',
    mobile: '0413 660 770',
    reference: ref(2),
    incomeSource: 'Salary',
    status: 'Lost - Manual Review',
    campaignSent: daysAgo(29),
    autoReplySent: daysAgo(27),
    replied: daysAgo(27),
    formSubmitted: daysAgo(24),
    invoiceId: 'INV-2026-0024',
    invoiceCreated: daysAgo(19),
    invoiceAmount: 129,
    fu1Sent: daysAgo(13),
    fu2Sent: daysAgo(7),
    fu3Sent: daysAgo(2),
    lastFollowUpDate: daysAgo(2),
    paymentReceived: 'no',
    notes: 'Email bounced on FU3 — possible bad address.',
  }),
];

// Bucket 8 — paid, onboarding sent (4)
const bucketOnboardingSent: Client[] = [
  client({
    srNo: 25,
    clientName: 'Nikhil Bhatia',
    email: 'nikhil.bhatia@gmail.com',
    mobile: '0418 220 605',
    reference: ref(0),
    incomeSource: 'Business',
    status: 'Onboarding Form Sent',
    campaignSent: daysAgo(22),
    autoReplySent: daysAgo(20),
    replied: daysAgo(20),
    formSubmitted: daysAgo(18),
    invoiceId: 'INV-2026-0025',
    invoiceCreated: daysAgo(10),
    invoiceAmount: 399,
    fu1Sent: 'no',
    fu2Sent: 'no',
    fu3Sent: 'no',
    paymentReceived: daysAgo(5),
    onboardingFormSent: daysAgo(4),
  }),
  client({
    srNo: 26,
    clientName: 'Grace Thompson',
    email: 'grace.thompson@outlook.com',
    mobile: '0436 991 117',
    reference: ref(1),
    incomeSource: 'Salary + Investment',
    status: 'Onboarding Form Sent',
    campaignSent: daysAgo(21),
    autoReplySent: daysAgo(19),
    replied: daysAgo(19),
    formSubmitted: daysAgo(17),
    invoiceId: 'INV-2026-0026',
    invoiceCreated: daysAgo(9),
    invoiceAmount: 179,
    fu1Sent: 'no',
    fu2Sent: 'no',
    fu3Sent: 'no',
    paymentReceived: daysAgo(4),
    onboardingFormSent: daysAgo(3),
  }),
  client({
    srNo: 27,
    clientName: 'Manish Tiwari',
    email: 'manish.tiwari@gmail.com',
    mobile: '0421 770 558',
    reference: ref(2),
    incomeSource: 'Salary',
    status: 'Onboarding Form Sent',
    campaignSent: daysAgo(23),
    autoReplySent: daysAgo(21),
    replied: daysAgo(21),
    formSubmitted: daysAgo(19),
    invoiceId: 'INV-2026-0027',
    invoiceCreated: daysAgo(11),
    invoiceAmount: 229,
    fu1Sent: daysAgo(4),
    fu2Sent: 'no',
    fu3Sent: 'no',
    lastFollowUpDate: daysAgo(4),
    paymentReceived: daysAgo(2),
    onboardingFormSent: daysAgo(1),
  }),
  client({
    srNo: 28,
    clientName: 'Ananya Kulkarni',
    email: 'ananya.kulkarni@outlook.com',
    mobile: '0408 660 882',
    reference: ref(0),
    incomeSource: 'Salary + Rental',
    status: 'Onboarding Form Sent',
    campaignSent: daysAgo(20),
    autoReplySent: daysAgo(18),
    replied: daysAgo(18),
    formSubmitted: daysAgo(16),
    invoiceId: 'INV-2026-0028',
    invoiceCreated: daysAgo(8),
    invoiceAmount: 199,
    fu1Sent: 'no',
    fu2Sent: 'no',
    fu3Sent: 'no',
    paymentReceived: daysAgo(3),
    onboardingFormSent: daysAgo(2),
  }),
];

// Bucket 9 — fully complete (2)
const bucketComplete: Client[] = [
  client({
    srNo: 29,
    clientName: 'Rajesh Khanna',
    email: 'rajesh.khanna@gmail.com',
    mobile: '0413 558 226',
    reference: ref(1),
    incomeSource: 'Salary + Investment',
    status: 'Onboarding Form Submitted',
    campaignSent: daysAgo(25),
    autoReplySent: daysAgo(23),
    replied: daysAgo(23),
    formSubmitted: daysAgo(20),
    invoiceId: 'INV-2026-0029',
    invoiceCreated: daysAgo(12),
    invoiceAmount: 449,
    fu1Sent: 'no',
    fu2Sent: 'no',
    fu3Sent: 'no',
    paymentReceived: daysAgo(7),
    onboardingFormSent: daysAgo(6),
    onboardingFormSubmitted: daysAgo(4),
    notes: 'Long-standing client; preferred email contact only.',
  }),
  client({
    srNo: 30,
    clientName: 'Sophie Williams',
    email: 'sophie.williams@outlook.com',
    mobile: '0426 117 558',
    reference: ref(2),
    incomeSource: 'Business',
    status: 'Onboarding Form Submitted',
    campaignSent: daysAgo(26),
    autoReplySent: daysAgo(24),
    replied: daysAgo(24),
    formSubmitted: daysAgo(21),
    invoiceId: 'INV-2026-0030',
    invoiceCreated: daysAgo(13),
    invoiceAmount: 499,
    fu1Sent: 'no',
    fu2Sent: 'no',
    fu3Sent: 'no',
    paymentReceived: daysAgo(8),
    onboardingFormSent: daysAgo(7),
    onboardingFormSubmitted: daysAgo(5),
  }),
];

export const mockClients: Client[] = [
  ...bucketCampaignOnly,
  ...bucketReplied,
  ...bucketFormSubmitted,
  ...bucketInvoiceSent,
  ...bucketFU1,
  ...bucketFU2,
  ...bucketLost,
  ...bucketOnboardingSent,
  ...bucketComplete,
];
